version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hasan82.13
    ports:
      - "5432:5432"

  bookmarket:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://db:5432/book_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=hasan82.13
    depends_on:
      - db
    ports:
      - "8082:8082"
